version: '3'
networks:
  lared:
    driver: bridge
services:
  backend:
    build: ./server
    environment:
      - CASSANDRA_SEEDS=cassandra-node-1,cassandra-node-2,cassandra-node-3
      - CASSANDRA_PASSWORD=cassandra
      - CASSANDRA_USER=cassandra
    depends_on:
      - cassandra-node-1
      - cassandra-node-2
      - cassandra-node-3
    networks:
      - lared
    ports:
      - "3000:3000"
  cassandra-node-1:
    image: bitnami/cassandra:4.0.4
    volumes:
      - ./Cassandra:/docker-entrypoint-initdb.d
    environment:
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_USER=cassandra
      - CASSANDRA_SEEDS=cassandra-node-1,cassandra-node-2,cassandra-node-3
      - CASSANDRA_PASSWORD=cassandra
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
    networks:
      - lared
    ports:
      - '9042:9042'

  cassandra-node-2:
    image: bitnami/cassandra:4.0.4
    environment:
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra
      - CASSANDRA_SEEDS=cassandra-node-1,cassandra-node-2,cassandra-node-3
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
    networks:
      - lared
    links:
      - cassandra-node-1
    ports:
      - '9142:9142'

  cassandra-node-3:
    image: bitnami/cassandra:4.0.4
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra-node-1,cassandra-node-2,cassandra-node-3
    networks:
      - lared
    links:
      - cassandra-node-1
    ports:
      - '9242:9242'
